print("salom1")
print("salom2")
print("salom3")
print("salom4")
print("salom5")
print("salom6")
print("salom7")
print("salom8")
print("salom9")
print("salom10")
print("salom11")
print("salom12")
print("salom13")
print("salom14")
print("salom15")
print("salom16")

